# Generated by Django 3.0.3 on 2020-03-25 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200324_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='JProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('poliorientation', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('poname', models.CharField(max_length=50, null=True)),
                ('numchallenge', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
