# Generated by Django 3.0.3 on 2020-03-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jprofile',
            name='poliorientation',
            field=models.CharField(choices=[('d', '선택안함'), ('co', '보수'), ('p', '진보'), ('ce', '중도')], default='d', help_text='정치성향', max_length=10, null=True),
        ),
    ]
