# Generated by Django 3.0.3 on 2020-03-31 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200401_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='jprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
