# Generated by Django 3.0.3 on 2020-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200401_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jprofile',
            name='department',
            field=models.CharField(choices=[('d', '선택안함'), ('OPC', '의정부'), ('MPM', '이조'), ('MSIT', '공조'), ('SPO', '사헌부'), ('BAI', '사간원'), ('NPA', '의금부')], default='d', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
