# Generated by Django 3.0.3 on 2020-04-03 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20200401_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPCKEY', models.IntegerField(default=0, null=True)),
                ('MPMKEY', models.IntegerField(default=0, null=True)),
                ('MSITKEY', models.IntegerField(default=0, null=True)),
                ('SPOKEY', models.IntegerField(default=0, null=True)),
                ('BAIKEY', models.IntegerField(default=0, null=True)),
                ('NPAKEY', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spear', models.IntegerField(default=0, null=True)),
                ('shield', models.IntegerField(default=0, null=True)),
                ('sword', models.IntegerField(default=0, null=True)),
                ('armor', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackcoin', models.IntegerField(default=0, null=True)),
                ('bluecoin', models.IntegerField(default=0, null=True)),
                ('greencoin', models.IntegerField(default=0, null=True)),
                ('orangecoin', models.IntegerField(default=0, null=True)),
                ('pinkcoin', models.IntegerField(default=0, null=True)),
                ('purplecoin', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPCcertificate', models.IntegerField(default=0, null=True)),
                ('MPMcertificate', models.IntegerField(default=0, null=True)),
                ('MSITcertificate', models.IntegerField(default=0, null=True)),
                ('SPOcertificate', models.IntegerField(default=0, null=True)),
                ('BAIcertificate', models.IntegerField(default=0, null=True)),
                ('NPAcertificate', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
