# Generated by Django 3.0.3 on 2020-04-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200404_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='BAIcertificate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='MPMcertificate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='MSITcertificate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='NPAcertificate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='OPCcertificate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='SPOcertificate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='bluecoin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='greencoin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='orangecoin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='pinkcoin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='purplecoin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='armor',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shield',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='spear',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sword',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jprofile',
            name='levels',
            field=models.PositiveIntegerField(choices=[(18, '從九品'), (17, '正九品'), (16, '從八品'), (15, '正八品'), (14, '從七品'), (13, '正七品'), (12, '從六品'), (11, '正六品'), (10, '從五品'), (9, '正五品'), (8, '從四品'), (7, '正四品'), (6, '從三品'), (5, '正三品'), (4, '從二品'), (3, '正二品'), (2, '從一品'), (1, '正一品')], default=18, null=True),
        ),
        migrations.AlterField(
            model_name='jprofile',
            name='numchallenge',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='key',
            name='BAIKEY',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='MPMKEY',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='MSITKEY',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='NPAKEY',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='OPCKEY',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='SPOKEY',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssindex',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
