# Generated by Django 3.0.3 on 2020-04-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20200404_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAIKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkey', models.PositiveIntegerField(default=2, null=True)),
                ('secondkey', models.PositiveIntegerField(default=1, null=True)),
                ('thirdkey', models.PositiveIntegerField(default=1, null=True)),
                ('fourthkey', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPMKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkey', models.PositiveIntegerField(default=3, null=True)),
                ('secondkey', models.PositiveIntegerField(default=3, null=True)),
                ('thirdkey', models.PositiveIntegerField(default=1, null=True)),
                ('fourthkey', models.PositiveIntegerField(default=1, null=True)),
                ('fifthkey', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MSITKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkey', models.PositiveIntegerField(default=3, null=True)),
                ('secondkey', models.PositiveIntegerField(default=3, null=True)),
                ('thirdkey', models.PositiveIntegerField(default=1, null=True)),
                ('fourthkey', models.PositiveIntegerField(default=1, null=True)),
                ('fifthkey', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPAKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkey', models.PositiveIntegerField(default=6, null=True)),
                ('secondkey', models.PositiveIntegerField(default=4, null=True)),
                ('thirdkey', models.PositiveIntegerField(default=2, null=True)),
                ('fourthkey', models.PositiveIntegerField(default=1, null=True)),
                ('fifthkey', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPCKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkey', models.PositiveIntegerField(default=1, null=True)),
                ('secondkey', models.PositiveIntegerField(default=1, null=True)),
                ('thirdkey', models.PositiveIntegerField(default=1, null=True)),
                ('fourthkey', models.PositiveIntegerField(default=1, null=True)),
                ('fifthkey', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPOKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkey', models.PositiveIntegerField(default=25, null=True)),
                ('secondkey', models.PositiveIntegerField(default=2, null=True)),
                ('thirdkey', models.PositiveIntegerField(default=2, null=True)),
                ('fourthkey', models.PositiveIntegerField(default=2, null=True)),
                ('fifthkey', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSITfirstkey', models.PositiveIntegerField(default=0, null=True)),
                ('MSITsecondkey', models.PositiveIntegerField(default=0, null=True)),
                ('MSITthirdkey', models.PositiveIntegerField(default=0, null=True)),
                ('MSITfourthkey', models.PositiveIntegerField(default=0, null=True)),
                ('MSITfifthkey', models.PositiveIntegerField(default=0, null=True)),
                ('MPMfirstkey', models.PositiveIntegerField(default=0, null=True)),
                ('MPMsecondkey', models.PositiveIntegerField(default=0, null=True)),
                ('MPMthirdkey', models.PositiveIntegerField(default=0, null=True)),
                ('MPMfourthkey', models.PositiveIntegerField(default=0, null=True)),
                ('MPMfifthkey', models.PositiveIntegerField(default=0, null=True)),
                ('BAIfirstkey', models.PositiveIntegerField(default=0, null=True)),
                ('BAIsecondkey', models.PositiveIntegerField(default=0, null=True)),
                ('BAIthirdkey', models.PositiveIntegerField(default=0, null=True)),
                ('BAIfourthkey', models.PositiveIntegerField(default=0, null=True)),
                ('SPOfirstkey', models.PositiveIntegerField(default=0, null=True)),
                ('SPOsecondkey', models.PositiveIntegerField(default=0, null=True)),
                ('SPOthirdkey', models.PositiveIntegerField(default=0, null=True)),
                ('SPOfourthkey', models.PositiveIntegerField(default=0, null=True)),
                ('SPOfifthkey', models.PositiveIntegerField(default=0, null=True)),
                ('NPAfirstkey', models.PositiveIntegerField(default=0, null=True)),
                ('NPAsecondkey', models.PositiveIntegerField(default=0, null=True)),
                ('NPAthirdkey', models.PositiveIntegerField(default=0, null=True)),
                ('NPAfourthkey', models.PositiveIntegerField(default=0, null=True)),
                ('NPAfifthkey', models.PositiveIntegerField(default=0, null=True)),
                ('OPCfirstkey', models.PositiveIntegerField(default=0, null=True)),
                ('OPCsecondkey', models.PositiveIntegerField(default=0, null=True)),
                ('OPCthirdkey', models.PositiveIntegerField(default=0, null=True)),
                ('OPCfourthkey', models.PositiveIntegerField(default=0, null=True)),
                ('OPCfifthkey', models.PositiveIntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jprofile',
            name='department',
            field=models.CharField(choices=[('d', '선택안함'), ('MSIT', '공조'), ('MPM', '이조'), ('BAI', '사간원'), ('SPO', '사헌부'), ('NPA', '의금부'), ('OPC', '의정부')], default='d', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
