# Generated by Django 3.0.3 on 2020-04-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_msitkey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msitkey',
            name='user',
        ),
    ]
