# Generated by Django 3.0.3 on 2020-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_msitkey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.PositiveIntegerField(default=3, null=True)),
                ('keystock', models.PositiveIntegerField(default=3, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BAIKEY',
        ),
        migrations.DeleteModel(
            name='MPMKEY',
        ),
        migrations.DeleteModel(
            name='MSITKEY',
        ),
        migrations.DeleteModel(
            name='NPAKEY',
        ),
        migrations.DeleteModel(
            name='OPCKEY',
        ),
        migrations.DeleteModel(
            name='SPOKEY',
        ),
        migrations.DeleteModel(
            name='UserKEY',
        ),
    ]
