# Generated by Django 3.0.3 on 2020-04-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
