# Generated by Django 3.0.3 on 2020-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_key_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='copykey',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
