# Generated by Django 3.0.3 on 2020-04-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200409_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jprofile',
            name='numchallenge',
        ),
        migrations.RemoveField(
            model_name='jprofile',
            name='poname',
        ),
    ]
