# Generated by Django 3.0.3 on 2020-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200409_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='getsword',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
