# Generated by Django 3.0.3 on 2020-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
