# Generated by Django 3.0.3 on 2020-04-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_bookmark_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
