# Generated by Django 3.0.3 on 2020-05-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_delete_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='keystock',
        ),
    ]
