# Generated by Django 3.0.3 on 2020-07-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20200520_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jprofile',
            name='department',
            field=models.CharField(choices=[('d', '선택안함'), ('MSIT', '공조'), ('MPM', '이조'), ('BAI', '사간원'), ('SPO', '사헌부'), ('NPA', '의금부')], default='d', max_length=10, null=True),
        ),
    ]
