# Generated by Django 3.0.3 on 2020-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20200711_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='letter',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
