# Generated by Django 3.0.3 on 2020-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20200724_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shieldOfGod',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='spearOfGod',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='swordOfGod',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
