# Generated by Django 3.0.3 on 2020-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200726_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='impeached',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='recommended',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
