# Generated by Django 3.0.3 on 2020-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20200726_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accused',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
