# Generated by Django 3.0.3 on 2020-08-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_item_accused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='armor',
            field=models.PositiveIntegerField(default=5, null=True),
        ),
    ]
