# Generated by Django 3.0.3 on 2020-08-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200802_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='SSkey',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
