# Generated by Django 3.0.3 on 2020-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_userkey_sskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranker',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
