# Generated by Django 3.0.3 on 2020-08-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20200802_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KEY',
        ),
        migrations.RemoveField(
            model_name='jprofile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ssindex',
        ),
    ]
