# Generated by Django 3.0.3 on 2020-08-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20200803_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranker',
            options={'ordering': ['-rankpoint']},
        ),
    ]
