# Generated by Django 3.0.3 on 2020-08-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20200804_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranker',
            name='ranking',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
