# Generated by Django 3.0.3 on 2020-08-04 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_remove_ranker_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='jprofile',
            name='anonymous_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
