# Generated by Django 3.0.3 on 2020-08-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_jprofile_anonymous_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jprofile',
            name='poliorientation',
        ),
        migrations.AddField(
            model_name='jprofile',
            name='political_orientation',
            field=models.CharField(choices=[('default', '선택안함'), ('conservatism', '보수'), ('progressivism', '진보'), ('centrism', '중도')], default='default', help_text='정치성향', max_length=15, null=True),
        ),
    ]
