# Generated by Django 3.0.3 on 2020-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20200805_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view_profile',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
