# Generated by Django 3.0.3 on 2020-09-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_item_view_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='view_profile',
        ),
        migrations.RemoveField(
            model_name='jprofile',
            name='anonymous_id',
        ),
    ]
