# Generated by Django 3.0.3 on 2020-09-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20200902_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jprofile',
            name='position',
            field=models.CharField(blank=True, default='없음', max_length=10, null=True),
        ),
    ]
