# Generated by Django 3.0.3 on 2020-09-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20200903_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_orientation', models.CharField(max_length=10)),
                ('number_user', models.PositiveIntegerField(default=0, null=True)),
                ('date_changed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
