# Generated by Django 3.0.3 on 2020-09-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_numberofuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberOfUser',
        ),
    ]
