# Generated by Django 3.0.3 on 2020-09-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_delete_numberofuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_orientation', models.CharField(max_length=10)),
                ('numberOfuser', models.PositiveIntegerField(default=0)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
