# Generated by Django 3.0.3 on 2020-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='numberOfuser',
            new_name='numberOfUser',
        ),
        migrations.AlterField(
            model_name='classification',
            name='political_orientation',
            field=models.CharField(max_length=15),
        ),
    ]
