# Generated by Django 3.0.3 on 2020-10-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20200910_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='numberOfUser',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
