# Generated by Django 3.0.3 on 2020-10-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20201028_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jprofile',
            name='political_orientation',
            field=models.CharField(choices=[('progressivism', '진보'), ('centrism', '중도/선택안함'), ('conservatism', '보수')], help_text='정치성향', max_length=15, null=True),
        ),
    ]
