# Generated by Django 3.0.3 on 2020-02-19 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200219_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 14, 29, 56, 637311, tzinfo=utc)),
        ),
    ]
