# Generated by Django 3.0.3 on 2020-02-19 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200219_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 14, 47, 3, 651052, tzinfo=utc)),
        ),
    ]
