# Generated by Django 3.0.3 on 2020-08-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200221_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
