# Generated by Django 3.0.3 on 2020-04-14 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0002_post_spear'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shield',
            field=models.ManyToManyField(blank=True, related_name='shield_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
