# Generated by Django 3.0.3 on 2020-04-17 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0003_post_shield'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='j_post_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
