# Generated by Django 3.0.3 on 2020-07-14 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0007_auto_20200713_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recommend',
            new_name='all_recommend',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='post',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='joseon_scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
