# Generated by Django 3.0.3 on 2020-07-14 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0008_auto_20200715_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down',
            field=models.ManyToManyField(blank=True, related_name='comment_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='up',
            field=models.ManyToManyField(blank=True, related_name='comment_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
