# Generated by Django 3.0.3 on 2020-07-15 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0009_auto_20200715_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='down',
            field=models.ManyToManyField(blank=True, related_name='joseon_comment_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up',
            field=models.ManyToManyField(blank=True, related_name='joseon_comment_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
