# Generated by Django 3.0.3 on 2020-07-26 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0010_auto_20200715_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shieldOfGod',
            field=models.ManyToManyField(blank=True, related_name='shieldOfGod_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='spearOfGod',
            field=models.ManyToManyField(blank=True, related_name='spearOfGod_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
