# Generated by Django 3.0.3 on 2020-07-29 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0014_post_ca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ca',
        ),
        migrations.AddField(
            model_name='post',
            name='nickname_check',
            field=models.ManyToManyField(blank=True, related_name='nickname_check', to=settings.AUTH_USER_MODEL),
        ),
    ]
