# Generated by Django 3.0.3 on 2020-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0015_auto_20200729_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
