# Generated by Django 3.0.3 on 2020-07-30 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0017_post_comment_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_nick',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joseon_comment_nickname', to=settings.AUTH_USER_MODEL),
        ),
    ]
