# Generated by Django 3.0.3 on 2020-07-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0020_comment_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentnickname',
            name='author',
        ),
    ]
