# Generated by Django 3.0.3 on 2020-07-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0021_remove_commentnickname_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_nickname',
        ),
        migrations.DeleteModel(
            name='CommentNickname',
        ),
    ]
