# Generated by Django 3.0.3 on 2020-08-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0024_auto_20200807_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(max_length=1400),
        ),
    ]
