# Generated by Django 3.0.3 on 2020-08-15 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joseon', '0025_auto_20200815_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credibility',
            field=models.ManyToManyField(blank=True, related_name='credibility_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='total_credibility',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
