# Generated by Django 3.0.3 on 2020-08-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0027_auto_20200819_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='content',
        ),
    ]
