# Generated by Django 3.0.3 on 2020-08-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0028_auto_20200819_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contents',
        ),
    ]
