# Generated by Django 3.0.3 on 2020-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0029_auto_20200819_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
