# Generated by Django 3.0.3 on 2020-11-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseon', '0030_auto_20201105_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
