from django.urls import path, include
from .views import (
    home,
    levelup,
    MSITlevelup,
    MPMlevelup,
    BAIlevelup,
    SPOlevelup,
    NPAlevelup,
    OPClevelup,
    shop,
    buySpear,
    buyShield,
    buySword,
    buyArmor,
    buyLetter,
    buyStar,
    buyReference_Letter,
    buyRefutation,
    buyImpeachment,
    buySpearOfGod,
    buyShieldOfGod,
    buySwordOfGod,
    buyImpeachment_Shield,
    buyRankPoint,
    buyMSIT,
    buyMPM,
    buyBAI,
    buySPO,
    buyNPA,
    buyOPC,
    buyMSITfirstkey,
    buyMSITsecondkey,
    buyMSITthirdkey,
    buyMSITfourthkey,
    buyMSITfifthkey,
    buyMPMfirstkey,
    buyMPMsecondkey,
    buyMPMthirdkey,
    buyMPMfourthkey,
    buyMPMfifthkey,
    buyBAIfirstkey,
    buyBAIsecondkey,
    buyBAIthirdkey,
    buyBAIfourthkey,
    buySPOfirstkey,
    buySPOsecondkey,
    buySPOthirdkey,
    buySPOfourthkey,
    buySPOfifthkey,
    buyNPAfirstkey,
    buyNPAsecondkey,
    buyNPAthirdkey,
    buyNPAfourthkey,
    buyNPAfifthkey,
    buyOPCfirstkey,
    buyOPCsecondkey,
    buyOPCthirdkey,
    buyOPCfourthkey,
    buyOPCfifthkey,
    buyOPCsixthkey,
    buyOPCseventhkey,
    buySSkey
)
app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('levelup/', levelup, name='levelup'),
    path('MSITlevelup/', MSITlevelup, name='MSITlevelup'),
    path('MPMlevelup/', MPMlevelup, name='MPMlevelup'),
    path('BAIlevelup/', BAIlevelup, name='BAIlevelup'),
    path('SPOlevelup/', SPOlevelup, name='SPOlevelup'),
    path('NPAlevelup/', NPAlevelup, name='NPAlevelup'),
    path('OPClevelup/', OPClevelup, name='OPClevelup'),
    path('shop/', shop, name='shop'),
    path('buySpear/', buySpear, name='buySpear'),
    path('buyShield/', buyShield, name='buyShield'),
    path('buySword/', buySword, name='buySword'),
    path('buyArmor/', buyArmor, name='buyArmor'),
    path('buyLetter/', buyLetter, name='buyLetter'),    
    path('buyStar/', buyStar, name='buyStar'),
    path('buyReference_Letter/', buyReference_Letter, name='buyReference_Letter'),
    path('buyRefutation/', buyRefutation, name='buyRefutation'),
    path('buySpearOfGod/', buySpearOfGod, name='buySpearOfGod'),
    path('buyImpeachment/', buyImpeachment, name='buyImpeachment'),
    path('buyShieldOfGod/', buyShieldOfGod, name='buyShieldOfGod'),
    path('buySwordOfGod/', buySwordOfGod, name='buySwordOfGod'),
    path('buyImpeachment_Shield/', buyImpeachment_Shield, name='buyImpeachment_Shield'),
    path('buyRankPoint/', buyRankPoint, name='buyRankPoint'),
    path('buyMSIT/', buyMSIT, name='buyMSIT'),
    path('buyMPM/', buyMPM, name='buyMPM'),
    path('buyBAI/', buyBAI, name='buyBAI'),
    path('buySPO/', buySPO, name='buySPO'),
    path('buyNPA/', buyNPA, name='buyNPA'),
    path('buyOPC/', buyOPC, name='buyOPC'),
    path('buyMSITfirstkey', buyMSITfirstkey, name='buyMSITfirstkey'),
    path('buyMSITsecondkey', buyMSITsecondkey, name='buyMSITsecondkey'),
    path('buyMSITthirdkey', buyMSITthirdkey, name='buyMSITthirdkey'),
    path('buyMSITfourthkey', buyMSITfourthkey, name='buyMSITfourthkey'),
    path('buyMSITfifthkey', buyMSITfifthkey, name='buyMSITfifthkey'),
    path('buyMPMfirstkey', buyMPMfirstkey, name='buyMPMfirstkey'),
    path('buyMPMsecondkey', buyMPMsecondkey, name='buyMPMsecondkey'),
    path('buyMPMthirdkey', buyMPMthirdkey, name='buyMPMthirdkey'),
    path('buyMPMfourthkey', buyMPMfourthkey, name='buyMPMfourthkey'),
    path('buyMPMfifthkey', buyMPMfifthkey, name='buyMPMfifthkey'),
    path('buyBAIfirstkey', buyBAIfirstkey, name='buyBAIfirstkey'),
    path('buyBAIsecondkey', buyBAIsecondkey, name='buyBAIsecondkey'),
    path('buyBAIthirdkey', buyBAIthirdkey, name='buyBAIthirdkey'),
    path('buyBAIfourthkey', buyBAIfourthkey, name='buyBAIfourthkey'),
    path('buySPOfirstkey', buySPOfirstkey, name='buySPOfirstkey'),
    path('buySPOsecondkey', buySPOsecondkey, name='buySPOsecondkey'),
    path('buySPOthirdkey', buySPOthirdkey, name='buySPOthirdkey'),
    path('buySPOfourthkey', buySPOfourthkey, name='buySPOfourthkey'),
    path('buySPOfifthkey', buySPOfifthkey, name='buySPOfifthkey'),
    path('buyNPAfirstkey', buyNPAfirstkey, name='buyNPAfirstkey'),
    path('buyNPAsecondkey', buyNPAsecondkey, name='buyNPAsecondkey'),
    path('buyNPAthirdkey', buyNPAthirdkey, name='buyNPAthirdkey'),
    path('buyNPAfourthkey', buyNPAfourthkey, name='buyNPAfourthkey'),
    path('buyNPAfifthkey', buyNPAfifthkey, name='buyNPAfifthkey'),
    path('buyOPCfirstkey', buyOPCfirstkey, name='buyOPCfirstkey'),
    path('buyOPCsecondkey', buyOPCsecondkey, name='buyOPCsecondkey'),
    path('buyOPCthirdkey', buyOPCthirdkey, name='buyOPCthirdkey'),
    path('buyOPCfourthkey', buyOPCfourthkey, name='buyOPCfourthkey'),
    path('buyOPCfifthkey', buyOPCfifthkey, name='buyOPCfifthkey'),
    path('buyOPCsixthkey', buyOPCsixthkey, name='buyOPCsixthkey'),
    path('buyOPCseventhkey', buyOPCseventhkey, name='buyOPCseventhkey'),
    path('buySSkey', buySSkey, name='buySSkey'),
]
