# Generated by Django 3.0.3 on 2020-07-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazylab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='pppp',
        ),
    ]
