# Generated by Django 3.0.3 on 2020-07-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazylab', '0002_auto_20200712_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pppp',
            new_name='text',
        ),
    ]
