# Generated by Django 3.0.3 on 2020-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazylab', '0003_auto_20200712_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=600),
        ),
    ]
