# Generated by Django 3.0.3 on 2020-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazylab', '0010_auto_20200715_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accused',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='accused',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
