# Generated by Django 3.0.3 on 2020-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazylab', '0015_auto_20201109_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crazylab_pics'),
        ),
    ]
