from django.urls import path
from django.conf.urls import url
from .views import (
    PoliticsListView,
    EconomyListView,
    SocietyListView,
    WorldListView,
    IdeologyListView,
    PhilosophyListView,
    LoveListView,
    BAIListView,
    SecretListView,
    joseon_detail,
    politics,
    economy,
    society,
    world,
    ideology,
    philosophy,
    love,
    BAI,
    secret,
    post_politics,
    post_economy,
    post_society,
    post_world,
    post_ideology,
    post_philosophy,
    post_love,
    post_BAI,
    post_secret,
    add_spear,
    add_shield,
    scrap,
    user_scrap,
    lower_credibility,
    add_spearOfGod,
    add_shieldOfGod,
    get_sword,
    recommended,
    impeached,
    get_swordOfGod,
    up_comment,
    down_comment
)

app_name = 'joseon'

urlpatterns = [
    path('politics', PoliticsListView.as_view(), name = 'politics_list'),
    path('economy', EconomyListView.as_view(), name = 'economy_list'),
    path('society', SocietyListView.as_view(), name = 'society_list'),
    path('world', WorldListView.as_view(), name = 'world_list'),
    path('ideology', IdeologyListView.as_view(), name = 'ideology_list'),
    path('philosophy', PhilosophyListView.as_view(), name = 'philosophy_list'),
    path('love' ,LoveListView.as_view(), name = 'love_list'),
    path('BAI', BAIListView.as_view(), name = 'BAI_list'),
    path('secret', SecretListView.as_view(), name = 'secret_list'),
    path('<int:pk>', joseon_detail, name='joseon_detail'),
    path('politics/', politics, name='politics'),
    path('economy/', economy, name='economy'),
    path('society/', society, name='society'),
    path('world/', world, name='world'),
    path('ideology/', ideology, name='ideology'),
    path('philosophy/', philosophy, name='philosophy'),
    path('love/', love, name='love'),
    path('BAI/', BAI, name='BAI'),
    path('secret/', secret, name='secret'),
    path('post_politics/', post_politics, name='post_politics'),
    path('post_economy/', post_economy, name='post_economy'),
    path('post_society/', post_society, name='post_society'),
    path('post_world/', post_world, name='post_world'),
    path('post_ideology/', post_ideology, name='post_ideology'),
    path('post_philosophy/', post_philosophy, name='post_philosophy'),
    path('post_love/', post_love, name='post_love'),
    path('post_BAI/', post_BAI, name='post_BAI'),
    path('post_secret/', post_secret, name='post_secret'),
    path('add_spear', add_spear, name='add_spear'),
    path('add_shield', add_shield, name='add_shield'),
    path('lower_credibility', lower_credibility, name='lower_credibility'),
    path('scrap', scrap, name='scrap'),
    path('user_scrap/<int:pk>', user_scrap, name='user_scrap'),
    path('add_spearOfGod', add_spearOfGod, name='add_spearOfGod'),
    path('add_shieldOfGod', add_shieldOfGod, name='add_shieldOfGod'),
    path('get_sword', get_sword, name="get_sword"),
    path('recommended', recommended, name="recommended"),
    path('impeached', impeached, name="impeached"),
    path('get_swordOfGod', get_swordOfGod, name='get_swordOfGod'),
    path('up_comment', up_comment, name='up_comment'),
    path('down_comment', down_comment, name='down_comment')
]
