# Generated by Django 3.0.3 on 2020-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommend',
            field=models.IntegerField(null=True),
        ),
    ]
