# Generated by Django 3.0.3 on 2020-03-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0004_auto_20200225_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
