# Generated by Django 3.0.3 on 2020-07-13 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reality', '0008_auto_20200713_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banana',
            field=models.ManyToManyField(blank=True, related_name='reality_banana', to=settings.AUTH_USER_MODEL),
        ),
    ]
