# Generated by Django 3.0.3 on 2020-07-14 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reality', '0009_post_banana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banana',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='post',
            name='all_recommend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='reality_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='recommend',
        ),
        migrations.AddField(
            model_name='post',
            name='recommend',
            field=models.ManyToManyField(blank=True, related_name='reality_recommend', to=settings.AUTH_USER_MODEL),
        ),
    ]
