# Generated by Django 3.0.3 on 2020-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0014_auto_20200814_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_submit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
