# Generated by Django 3.0.3 on 2020-08-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0016_auto_20200814_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.DeleteModel(
            name='RealityUser',
        ),
    ]
