# Generated by Django 3.0.3 on 2020-08-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0017_auto_20200815_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='down',
        ),
    ]
